version: '3.5'
services:
    technitium-dns:
        container_name: technitium_dns
        hostname: tdns
        user: ContainerAdministrator
        network_mode: External
        volumes:
            - 'X:\technitium-dns\config:C:\app\config'
            - 'X:\technitium-dns\certs:C:\certs'
        restart: unless-stopped
        image: 'cspeers/technitium-dns:latest'
        mac_address: 00:15:33:12:33:33
networks:
    default:
      external: 
          name: External        